// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXIocx3mttGy9vWNhTKKRTSSDDHd1uBME',
    appId: '1:999129230168:android:4048f302291dad6418532d',
    messagingSenderId: '999129230168',
    projectId: 'whattodo-30c71',
    databaseURL: 'https://whattodo-30c71-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'whattodo-30c71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxzuR4CnNWBQx8fvKYuwcAQmLzHXf1IdY',
    appId: '1:999129230168:ios:98e3f39c27955c9618532d',
    messagingSenderId: '999129230168',
    projectId: 'whattodo-30c71',
    databaseURL: 'https://whattodo-30c71-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'whattodo-30c71.firebasestorage.app',
    iosBundleId: 'co.whattodo.whattodo',
  );
}
